# Generated by Django 5.2.17 on 2026-08-14 09:24

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FloodZone',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=180)),
                ('state', models.CharField(max_length=120)),
                ('river', models.CharField(max_length=120)),
                ('risk', models.CharField(choices=[('SEVERE', 'Severe'), ('HIGH', 'High'), ('MODERATE', 'Moderate')], max_length=16)),
                ('probability', models.FloatField()),
                ('radius_km', models.FloatField()),
                ('center', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('forecast', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ReliefCamp',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=180)),
                ('district', models.CharField(max_length=120)),
                ('state', models.CharField(max_length=120)),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('occupancy', models.PositiveIntegerField(default=0)),
                ('food_days', models.FloatField(default=0)),
                ('water_days', models.FloatField(default=0)),
                ('medical_staff', models.PositiveIntegerField(default=0)),
                ('urgent', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('STABLE', 'Stable'), ('STRAINED', 'Strained'), ('CRITICAL', 'Critical')], default='STABLE', max_length=16)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RescueResource',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('type', models.CharField(max_length=40)),
                ('agency', models.CharField(max_length=160)),
                ('category', models.CharField(max_length=16)),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('base', models.CharField(max_length=160)),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('capabilities', models.JSONField(default=list)),
                ('availability', models.CharField(choices=[('AVAILABLE', 'Available'), ('ENGAGED', 'Engaged'), ('MAINTENANCE', 'Maintenance')], default='AVAILABLE', max_length=16)),
                ('verified', models.BooleanField(default=False)),
                ('contact', models.CharField(blank=True, max_length=120)),
                ('last_update', models.CharField(blank=True, max_length=80)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SOSRequest',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('channel', models.CharField(max_length=8)),
                ('raw', models.TextField(blank=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('place', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=120)),
                ('state', models.CharField(max_length=120)),
                ('people', models.PositiveIntegerField(default=1)),
                ('children', models.PositiveIntegerField(default=0)),
                ('elderly', models.PositiveIntegerField(default=0)),
                ('disabled', models.PositiveIntegerField(default=0)),
                ('livestock', models.PositiveIntegerField(default=0)),
                ('flood_depth_m', models.FloatField(default=0)),
                ('medical', models.BooleanField(default=False)),
                ('received_at', models.CharField(max_length=80)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('TRIAGED', 'Triaged'), ('ASSIGNED', 'Assigned'), ('DISPATCHED', 'Dispatched'), ('RESCUED', 'Rescued'), ('CLOSED', 'Closed')], default='NEW', max_length=16)),
                ('factors', models.JSONField(default=list)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='response.rescueresource')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackEntry',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=80)),
                ('by', models.CharField(max_length=160)),
                ('at', models.CharField(max_length=40)),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='response.sosrequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
